name: deploy-gh-pages
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.13.0
      - run: npm install
      - run: npm run generate
        env:
         CHARGETRIP_API_URL: ${{ secrets.CHARGETRIP_API_URL }}
         ALGOLIA_API_SECRET_KEY: ${{ secrets.ALGOLIA_API_SECRET_KEY }}
         ALGOLIA_API_PUBLIC_KEY: ${{ secrets.ALGOLIA_API_PUBLIC_KEY }}
         ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
         EDIT_API_URL: ${{ secrets.EDIT_API_URL }}
         EDIT_GITHUB_URL: ${{ secrets.EDIT_GITHUB_URL }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
